language: erlang

otp_release:
  - 20.3
  - 21.2

script:
  - rebar3 do eunit, dialyzer, lint

deploy:
  provider: script
  script: scripts/hex.sh
  on:
    tags: true

cache:
  directories:
    - $HOME/.cache/rebar3
